<a href="https://colab.research.google.com/github/poojya100/1BM23CS303_BIS_LAB/blob/main/BisLab_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

def application(grid_size, max_iter):
    INF = 1e12


    source = (0, 0)
    destination = (grid_size - 1, grid_size - 1)


    np.random.seed(42)
    cost_matrix = np.random.randint(1, 10, size=(grid_size, grid_size))

    # Initialize state grid
    state = np.full((grid_size, grid_size), INF)
    state[destination] = 0


    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    def get_neighbors(i, j):
        """Return valid adjacent cells."""
        nb = []
        for dx, dy in directions:
            ni, nj = i + dx, j + dy
            if 0 <= ni < grid_size and 0 <= nj < grid_size:
                nb.append((ni, nj))
        return nb

    # Parallel Cellular Update Loop
    for it in range(max_iter):
        new_state = state.copy()

        # Update every cell in parallel fashion
        for i in range(grid_size):
            for j in range(grid_size):
                if (i, j) == destination:
                    continue

                neighbor_costs = [
                    cost_matrix[ni, nj] + state[ni, nj]
                    for ni, nj in get_neighbors(i, j)
                ]

                if neighbor_costs:
                    new_state[i, j] = min(neighbor_costs)


        if np.allclose(new_state, state):
            print(f"Converged after {it} iterations.")
            break

        state = new_state


    path = [source]
    current = source

    while current != destination:
        i, j = current
        nbs = get_neighbors(i, j)
        next_cell = min(nbs, key=lambda n: state[n])
        path.append(next_cell)
        current = next_cell


    print("\nFinal Routing Cost Grid (State):")
    print(np.round(state, 2))

    print("\nShortest Path:")
    print(" → ".join([str(p) for p in path]))

    print(f"\nTotal Cost from Source → Destination: {state[source]}")



if __name__ == "__main__":
    grid_size = int(input("Enter grid size (e.g., 20 for 20x20): "))
    max_iter = int(input("Enter max iterations (e.g., 500): "))

    application(grid_size, max_iter)


Enter grid size (e.g., 20 for 20x20): 7
Enter max iterations (e.g., 500): 15
Converged after 12 iterations.

Final Routing Cost Grid (State):
[[42. 38. 35. 36. 32. 29. 27.]
 [38. 33. 31. 28. 28. 26. 21.]
 [33. 31. 23. 22. 26. 21. 20.]
 [30. 23. 22. 19. 21. 18. 11.]
 [27. 22. 19. 12. 16.  9.  4.]
 [25. 21. 12. 10.  7.  4.  2.]
 [25. 18. 10.  7.  6.  2.  0.]]

Shortest Path:
(0, 0) → (1, 0) → (2, 0) → (3, 0) → (3, 1) → (4, 1) → (4, 2) → (5, 2) → (6, 2) → (6, 3) → (6, 4) → (6, 5) → (6, 6)

Total Cost from Source → Destination: 42.0
